"""add payment tracking to rentals

Revision ID: 6eab75c312a0
Revises: 8a3ea90ea57f
Create Date: 2026-05-05 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eab75c312a0'
down_revision: Union[str, Sequence[str], None] = '8a3ea90ea57f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	# Add columns to rental table
	op.add_column(
		'rental',
		sa.Column('actual_return_date', sa.DateTime(), nullable=True)
	)
	op.add_column(
		'rental',
		sa.Column(
			'payment_status',
			sa.String(length=20),
			nullable=False,
			server_default='pending'
		)
	)
	op.add_column(
		'rental',
		sa.Column('payment_amount', sa.Integer(), nullable=False, server_default='0')
	)

	# Create stripe_customers table
	op.create_table(
		'stripe_customers',
		sa.Column('id', sa.Integer(), nullable=False),
		sa.Column('user_id', sa.Integer(), nullable=False),
		sa.Column('stripe_customer_id', sa.String(), nullable=False),
		sa.Column('created_at', sa.DateTime(), nullable=False),
		sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
		sa.PrimaryKeyConstraint('id'),
		sa.UniqueConstraint('user_id'),
		sa.UniqueConstraint('stripe_customer_id'),
	)

	# Create payments table
	op.create_table(
		'payments',
		sa.Column('id', sa.Integer(), nullable=False),
		sa.Column('rental_id', sa.Integer(), nullable=False),
		sa.Column('stripe_payment_intent_id', sa.String(), nullable=False),
		sa.Column('amount', sa.Integer(), nullable=False),
		sa.Column('status', sa.String(length=20), nullable=False),
		sa.Column('currency', sa.String(), nullable=False, server_default='brl'),
		sa.Column('refunded_amount', sa.Integer(), nullable=False, server_default='0'),
		sa.Column('created_at', sa.DateTime(), nullable=False),
		sa.Column('updated_at', sa.DateTime(), nullable=False),
		sa.ForeignKeyConstraint(['rental_id'], ['rental.id'], ),
		sa.PrimaryKeyConstraint('id'),
		sa.UniqueConstraint('rental_id'),
		sa.UniqueConstraint('stripe_payment_intent_id'),
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_table('payments')
	op.drop_table('stripe_customers')
	op.drop_column('rental', 'payment_amount')
	op.drop_column('rental', 'payment_status')
	op.drop_column('rental', 'actual_return_date')
	# ### end Alembic commands ###
